apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/juliogrativol/demo-argocd.git
    targetRevision: HEAD
    path: java-app-rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
