apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/juliogrativol/demo-argocd.git
    targetRevision: HEAD
    path: guestbook  # ajuste aqui com base no seu repositório
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true          # remove recursos que foram deletados do Git
      selfHeal: true       # corrige mudanças feitas fora do Git
